### ISSUE TITLE
Epic: Release vaadin-crud

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-crud#1]
### MVP (First sprint)
- [x] Create Repo from skeleton
- [x] implement autogenerated grid
- [x] implement slotted grid
- [x] implement open editor in dialog when click
- [x] implement slotted form
- [x] basic demos: simple demo, custom grid, custom form.
- [x] implement new, save, delete with items array
- [x] implement form validation
- [ ] implement confirmation on delete and cancel
- [ ] Update license in html file header and package.json
- [ ] Register repo in zenhub, reviewable, travis ...

### MVP Validation
- [ ] validate design and API with PM
- [ ] unit tests
- [ ] visual tests

### Alpha-1
- [ ] implement dataProvider
- [ ] implement events on actions (with defaultPrevented checks)
- [ ] improve visual styles (validate with designers)
- [ ] validate API with flow
- [ ] documentation

### Beta-1
- [ ] DX tests
- [ ] P3
- [ ] Docs

**Comment by manolo** [comment]
Moved to #17
