### ISSUE TITLE
New Component <vaadin-crud>

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-crud#17]
DoD Doc: https://docs.google.com/spreadsheets/d/1pVu-DArshQI2WNd6y9ho85eIM8QmHixZQRZwRLXJqYM/edit#gid=1951044936
Design Doc: https://docs.google.com/document/d/1T4FTe8BAqaT9759jAcpj0ddj82u7Ol2F4yc-4twIITg/edit
Some visual Mocks: https://app.zeplin.io/project/5937d86d3601d452f1b8e66a/dashboard 

### MVP (First sprint)
- [x] Create Repo from skeleton
- [x] implement autogenerated grid
- [x] implement slotted grid
- [x] implement open editor in dialog when click
- [x] implement slotted form
- [x] basic demos: simple demo, custom grid, custom form.
- [x] implement new, save, delete with items array
- [x] implement form validation
- [x] implement confirmation on delete and cancel
- [x] Update license in html file header and package.json
- [x] Register repo in zenhub, reviewable, travis ...

### MVP Validation
- [x] validate design and API with PM
- [x] unit tests
- [x] visual tests

### Alpha-1
- [x] implement dataProvider
- [x] implement events on actions (with defaultPrevented checks)
- [x] improve visual styles (validate with designers)
- [x] validate API with flow
- [x] documentation

### Beta-1
- [x] DX tests
- [x] P3
- [x] Docs
